In [1]:
import numpy as np
import pandas as pd

In [2]:
prob_x = np.random.randint(low=0, high=100, size=(8,8))
prob_y = np.random.randint(low=0, high=100, size=(8,8))
prob_z = np.random.randint(low=0, high=100, size=(8,8))
all_probs = np.stack([prob_x, prob_y,  prob_z], axis=0)

prob_x, prob_y, prob_z, all_probs

(array([[46, 42, 86, 97, 70, 66, 25, 23],
        [70, 56, 45, 10, 89, 62, 31, 41],
        [47, 55, 82, 61, 81,  3, 41, 43],
        [ 6, 12, 39, 31, 40,  0, 16, 81],
        [38, 84, 53, 79, 65, 11,  0,  4],
        [50, 21, 78, 42, 71, 28, 55, 35],
        [69, 31, 18, 89, 21, 57, 45, 39],
        [41, 89,  9, 40, 74,  6, 42, 21]]),
 array([[50, 49, 96, 56, 63, 35, 29, 73],
        [14, 32, 99, 38, 58, 68, 31, 65],
        [61, 64, 76, 97,  3, 76, 88, 86],
        [44, 12, 76,  6, 49, 33, 95, 59],
        [21, 35, 34, 46, 82, 80,  6, 77],
        [32,  3,  5, 15, 83, 60, 38, 33],
        [20, 62, 67, 22,  9, 72, 98, 73],
        [51, 44, 43, 63, 69, 86, 26, 42]]),
 array([[60,  7, 95, 35,  1, 89, 92, 57],
        [39, 47, 23, 40, 13, 59, 64, 54],
        [70, 71, 83, 75, 55,  2, 70, 46],
        [87, 79, 53, 15, 77, 93, 41, 97],
        [59,  5, 31, 16, 73, 56, 54, 72],
        [47, 14, 65, 92, 11, 31, 89,  9],
        [72, 33, 12,  6, 95, 57, 53, 45],
        [39, 32, 19, 89, 43, 7

In [3]:
all_dev = np.std(all_probs, axis=1)

In [4]:
pd.DataFrame(all_dev)

0          1          2          3          4          5  \
0  18.744583  26.066022  27.275218  28.541363  20.990697  26.487910   
1  16.155011  20.475214  30.282008  27.642528  28.648735  18.646380   
2  15.885823  26.234519  29.150204  32.449961  32.634338  28.163585   

           6          7  
0  16.616539  20.996652  
1  33.940895  16.896745  
2  20.135479  23.374332