In [12]:
import numpy as np
import pandas as pd

In [31]:
prob_x = np.random.randint(low=0, high=100, size=(8,8))
prob_y = np.random.randint(low=0, high=100, size=(8,8))
prob_z = np.random.randint(low=0, high=100, size=(8,8))
all_probs = np.stack([prob_x, prob_y,  prob_z], axis=0)

prob_x, prob_y, prob_z, all_probs

(array([[70, 56, 40, 34, 81, 69, 22, 60],
        [34, 33, 35, 89, 51, 79, 19, 53],
        [ 6, 46, 64, 75, 90, 86, 50, 71],
        [84, 93, 93,  6, 36, 42, 30, 26],
        [27, 34, 90, 19, 54, 20, 17, 19],
        [ 6, 41,  6, 66, 89, 95,  5, 50],
        [16, 20, 52, 31, 47,  0, 95, 30],
        [61, 65, 50, 20, 80, 95, 82, 83]]),
 array([[87, 30, 62, 39, 35, 30, 73, 59],
        [69, 94,  0, 33, 61, 18, 56, 75],
        [55, 69, 23, 90, 32, 17, 49, 91],
        [29, 79, 12, 46, 55, 13, 98, 65],
        [83, 77, 41, 99,  4, 81, 79, 46],
        [48,  8, 88, 87, 51, 16, 84, 44],
        [67, 46, 38, 47, 50, 10, 50, 94],
        [90, 40,  5, 65, 74, 18, 70, 96]]),
 array([[ 3, 41, 26, 36, 80,  2, 55, 61],
        [60, 62, 58, 89, 10, 77,  1, 26],
        [56, 19, 11, 90, 57, 44,  9, 19],
        [56, 14, 98, 12, 52, 70, 26, 25],
        [68, 30, 98, 47, 78, 41, 66, 83],
        [29, 37, 30, 24, 91, 75, 55, 92],
        [11, 13, 76, 17, 47, 86, 86, 97],
        [25, 51, 61,  5, 77, 9

In [34]:
all_dev = np.std(all_probs, axis=1)

In [40]:
pd.DataFrame(all_dev)

0          1          2          3          4          5  \
0  28.146936  21.313141  26.920020  28.209041  19.862024  33.703672   
1  19.780040  27.193462  28.208764  24.045530  20.023424  21.713691   
2  23.005434  16.620300  30.711358  31.144823  24.233242  28.037642   

           6          7  
0  30.634947  21.118712  
1  16.228351  19.696129  
2  28.288690  30.380658